gui:
  theme:
    lightTheme: false # For terminals with a light background
    # activeBorderColor:
    #   - cyan
    #   - bold
    # inactiveBorderColor:
    #   - white
    # optionsTextColor:
    #   - blue
    # selectedLineBgColor:
    #   - default
    # selectedRangeBgColor:
    #   - blue
  showFileTree: false # for rendering changes files in a tree format
  authorColors: # in case you're not happy with the randomly assigned colour
    'Fida': '#0000FF'
